require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "Guardfile"
    - "db/**/*"
    - "config/**/*"
    - "spec/support/*.rb"
    - "spec/*.rb"
    - "node_modules/**/*"
    - "bin/**/*/"
    - "vendor/**/*"
    - "lib/tasks/**/*"
    - "lib/extensions/**/*"

Lint/MissingSuper:
  Exclude:
    - "app/frontend/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

RSpec/ImplicitExpect:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
